NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

import logging


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    # path('profiles/', include('news.urls')),
    # path('', include('django.contrib.auth.urls')),
    # path('login/', auth_views.LoginView.as_view()),
    # path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),

]

logger_dr = logging.getLogger('django.request')
logger_cn = logging.getLogger('django')

logger_dr.error("Hello! I'm an error in your app. Enjoy:)")
logger_cn.error("Hello! I'm another error in your app. Enjoy:)")

news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (
   PostsList,
   PostDetail,
   PostCreate,
   CategoryDetail,
   create_post,
   PostUpdate,
   PostDelete,
   PostSearchView,
   PostAuthor,
   subscribe_to_category,
   unsubscribe_from_category,
   PostType,
   PostTag, subscribe_to_author, unsubscribe_from_author
)

# нужно добавлять кэширование напрямую в urls.py (в котором хранятся именно сами представления, 
# а не основной urls.py из папки с settings.py
from django.core.cache import cache
from django.views.decorators.cache import cache_page


app_name = 'news'
urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   
   # с кешем (раскомментить для кеширования высокоуровневого)
   # path('', cache_page(60*1)(PostsList.as_view()), name='post_list'),
   # path('<int:pk>', cache_page(60*5)(PostDetail.as_view()), name='post_detail'),
   # path('author/<int:pk>', cache_page(60*5)(PostAuthor.as_view()), name='author_name'),
   # path('tag/<int:pk>', cache_page(60*5)(PostTag.as_view()), name='post_tag'),
   # path('type/<str:title>', cache_page(60*5)(PostType.as_view()), name='post_type'),
      
   # без кеша (кешируем на низком уровне)
   path('', PostsList.as_view(), name='post_list'),
   path('<int:pk>', PostDetail.as_view(), name='post_detail'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('search/', PostSearchView.as_view(), name='post_search'),
   path('author/<int:pk>', PostAuthor.as_view(), name='author_name'),
   path('subscribe/category/<int:pk>', subscribe_to_category, name='sub_cat'),
   path('unsubscribe/category/<int:pk>', unsubscribe_from_category, name='unsub_cat'),
   path('subscribe/author/<int:pk>', subscribe_to_author, name='sub_author'),
   path('unsubscribe/author/<int:pk>', unsubscribe_from_author, name='unsub_author'),
   path('tag/<int:pk>', PostTag.as_view(), name='post_tag'),
   path('type/<str:title>', PostType.as_view(), name='post_type'),
   
   # ненужные урлы
   # path('profile_update/', ProfileUpdate.as_view(), name='profile_update'),
   # path('accounts/profile/', ProfileUpdate.as_view(), name='profile_update'),
   # path('post/<int:pk>', PostDetail.as_view(), name='post_detail'),
   # path('create/', create_post, name='post_create'),
   # path('add/', PostCreate.as_view(), name='post_create'),
   # path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
]

news/models.py
from django.db import models
# from django.utils import timezone
from datetime import datetime, date, time
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    rating = models.SmallIntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscribers = models.ManyToManyField(
        User,
        through='AuthorSubscribers',
        blank=True,
        related_name='%(app_label)s_%(class)s_related',
        related_query_name='%(app_label)s_%(class)ss',
    )

    def update_rating(self):
        posts_rating = self.post_set.aggregate(post_rating_aggr=Sum('rating'))
        posts_rating_sum = 0
        posts_rating_sum += posts_rating.get('post_rating_aggr')

        comments_rating = self.user.comment_set.aggregate(comments_rating_aggr=Sum('rating'))
        comments_rating_sum = 0
        comments_rating_sum += comments_rating.get('comments_rating_aggr')

        self.rating = posts_rating_sum * 3 + comments_rating_sum

        # author_posts = self.post_set.all()
        # for post in author_posts:
        #     self.rating += post.rating * 3
        #     post_comments = post.comment_set.all()
        #     for comment in post_comments:
        #         self.rating += comment.rating

        self.save()
        return self.rating

    def subscribe(self):
        pass

    # Возвращает автора с лучшим рейтингом
    @staticmethod
    def best_author():
        return Author.objects.all().order_by('-rating')[0]

    def __str__(self):
        return f'{self.user.username}, rating = {self.rating}'

    class Meta:
        pass


class Category(models.Model):
    cat_name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, through='CategorySubscribers', blank=True)

    def subscribe(self):
        pass

    def get_category(self):
        return self.cat_name

    def __str__(self):
        return f'{self.cat_name}'

    def is_subscribed(self):
        self.subscribers.user.id
        cat = Category.objects.get(id=pk)
        return cat.subscribers.filter(id=user.id).exists()

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class CategorySubscribers(models.Model):
    subscriber_thru = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    category_thru = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    def get_user(self):
        return self.subscriber_thru

    def extract_category(self):
        return self.category_thru.cat_name

    def get_category(self):
        return self.category_thru

    def __str__(self):
        return f'{self.subscriber_thru} <-> {self.category_thru.cat_name}'


class AuthorSubscribers(models.Model):
    subscriber_thru = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    author_thru = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)

    def get_user(self):
        return self.subscriber_thru

    def extract_category(self):
        return self.author_thru.user.username

    def get_category(self):
        return self.author_thru

    def __str__(self):
        return f'{self.subscriber_thru} <-> {self.author_thru.user.username}'


class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NW'

    POST_CHOICES = [
        (ARTICLE, 'article'),
        (NEWS, 'news')
    ]

    type = models.CharField(max_length=2, choices=POST_CHOICES, default=NEWS)
    time_pub = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=128)
    body = models.TextField()
    rating = models.SmallIntegerField(default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    cats = models.ManyToManyField(Category, through='PostCategory')
    isUpdated = models.BooleanField(default=False)

    def __str__(self):
        num_of_comments = len(self.comment_set.all())
        post_metadata = f"'{self.title}' by {self.author.user.username},\n \
                          published on: {self.time_pub.strftime('%d/%m/%Y, %H:%M')},\n \
                          the rating of this post is {self.rating}\nPreview: {self.preview()}.\n \
                          It has {num_of_comments} comments."
        return post_metadata
        # return f'ID: {self.id}, Title: {self.title}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.body) > 124:
            return f'{self.body[:124]}...'
        return f'{self.body}'

    def get_absolute_url(self):
        # return f'/posts/{self.id}'
        return reverse('post_detail', args=[str(self.id)])

    def email_preview(self):
        if len(self.body) > 51:
            return f'{self.body[:51]}...'
        return f'{self.body}'

    def get_cat(self):
        return '\n'.join([c.cat_name for c in self.cats.all()])  # f'{self.type}'
    
    def save(self, *args, **kwargs):
        self.isUpdated = False
        super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его    


class Comment(models.Model):
    body = models.TextField()
    time_pub = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        comment_metadata = f"{self.user.username} wrote: '{self.body[:64]}',\n \
                             on: {self.time_pub.strftime('%d-%m-%Y, %H:%M')},\n \
                             the rating of this comment is {self.rating}\n"
        return comment_metadata


class PostCategory(models.Model):
    post_thru = models.ForeignKey(Post, on_delete=models.CASCADE)
    cat_thru = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.cat_thru} <-> {self.post_thru.title}'

templates/filtered.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %} Posts {% endblock title %}

{% block content %}

<h3 class="content-subhead">
  Found {{ filter.qs|length }} posts on query:
  <span>{{ name }}</span>
</h3>

{% if name.id %}
    {% if is_subscribed %}
        <div class="subscribe">
          <strong>
            You are already subscribed to <em>{{ name }}</em>. Unsubscribe?
            {% if subscription_object == 'category_subscription' %}
                  </strong>
                  <a href="{% url 'news:unsub_cat' name.id %}">
                    <button class="pure-button button-success" style="border-radius: 15px">
                      <i class="bi bi-bookmark-plus"></i>
                      Unsubscribe
                    </button>
                  </a>
            {% endif %}
            {% if subscription_object == 'author_subscription' %}
                    </strong>
                    <a href="{% url 'news:unsub_author' name.id %}">
                    <button class="pure-button button-success" style="border-radius: 15px">
                      <i class="bi bi-bookmark-plus"></i>
                      Unsubscribe
                    </button>
                  </a>
            {% endif %}
        </div>
    {% else %}
        <div class="subscribe">
          <strong>
            Do you want to subscribe to <em>{{ name }}</em>?
            {% if subscription_object == 'category_subscription' %}
                  </strong>
                  <a href="{% url 'news:sub_cat' name.id %}">
                    <button class="pure-button button-success" style="border-radius: 15px">
                      <i class="bi bi-bookmark-plus"></i>
                      Subscribe
                    </button>
                  </a>
            {% endif %}
            {% if subscription_object == 'author_subscription' %}
                    </strong>
                    <a href="{% url 'news:sub_author' name.id %}">
                    <button class="pure-button button-success" style="border-radius: 15px">
                      <i class="bi bi-bookmark-plus"></i>
                      Subscribe
                    </button>
                  </a>
            {% endif %}
        </div>
    {% endif %}
{% endif %}


{% if posts %}
    {% for post in posts %}

    <!--  A single blog post -->
    <section class="post">
      <header class="post-header"> <!--  <img class="post-avatar" src="/{{  post.author.avatar }}" alt="avatar" /> -->
        <a href="{% url 'news:post_detail' post.id %}">
          <h2 class="post-title">{{post.title|censor}}</h2>
        </a>
        <p class="post-meta">By
          <a class="post-author" href="{% url 'news:author_name' post.author_id %}">
            {{ post.author }}
          </a>
          on
          <em>{{ post.time_pub|date:'d M Y H:i' }}
          </em>
    <!--      Type:-->
    <!--      <a class="post-category post-type-{{post.type}}" href="{% url 'news:post_type' post.type %}">-->
    <!--        <span>-->
    <!--          {{post.get_type_display}}-->
    <!--        </span>-->
    <!--      </a>-->
          Categories:
          {% for cat in post.cats.values %}
              <a href="{% url 'news:post_tag' cat.id %}">
                {{ cat.cat_name }}</a> :
                <a></a>
          {%endfor%}
        </p>
      </header>
      <div class="post-description">
        <p>{{ post.body|censor | truncatewords:25 }}</p>
        <p><em>Post rating: {{post.rating}} </em></p>
      </div>
    </section>
    <hr />

    {%endfor%}
{% else %}
    <h2>There are no posts!</h2>
{% endif %}

   {# Добавляем пагинацию на страницу #}

     <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="?{% url_replace page=1 %}" tabindex="-1">FIRST</a>
            </li>
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?{% url_replace page=page_obj.previous_page_number %}{% endif %} " tabindex="-1">Previous</a>
            </li>

            {% if page_obj.number|add:'-4' > 1 %}
                <li class="page-item disabled"><a class="page-link" href="?{% url_replace page=page_obj.number|add:'-5' %}">&hellip;</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item disabled"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
                {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                    <li class="page-item"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                <li class="page-item disabled"><a class="page-link" href="?{% url_replace page=page_obj.number|add:'5' %}">&hellip;</a></li>
            {% endif %}

            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} ?{% url_replace page=page_obj.next_page_number %} {% endif %}">Next</a>
            </li>
            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} ?{% url_replace page=page_obj.paginator.num_pages %}  {% endif %}">LAST</a>
            </li>
        </ul>
    </nav>

<hr>

{% endblock content %}

templates/main.html
{% extends 'flatpages/default.html' %}
<html>
    <head>
        <title>Sign-Up / Sign-In</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Sign-Up / Sign-In</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/newpost.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Friendly Reminder</title>
</head>

<body>
  <h1>News Portal subscription</h1>
  <p>In category: <strong>"{{category_object.cat_name}}"</strong> there is a new post by
    <strong>{{post_object.author}}</strong>.
  </p>
  <a href="https://newsportal.com{% url 'news:post_detail' post_object.id %}">
    <h2>{{post_object.title}}</h2>
  </a>
  <p>{{post_object.email_preview}}</p>

</body>

</html>

templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h2>{{ post.title|censor }}</h2
<h3>{{ post.body|censor }}</h3>
<h4>Published on: {{ post.time_pub|date:'d M Y H:i' }}</h4>
<h5>By: {{ post.author }}</h5>
<h6>Categories: {% for cat in post.cats.all %} {{ cat }} : {% endfor %}</h6>
<hr>
<h4>Comments:</h4>

<hr>
{% if post.comment_set.all|length > 0 %}

    {% for comment in post.comment_set.all  %}

        {{ comment.user.username }} wrote: {{ comment.body|censor }}
        on: {{ comment.time_pub }} The rating of the comment is {{ comment.rating }}.

        <hr><br>

    {% endfor %}
{% else %}
    No comments!

{% endif %}

{% endblock content %}

templates/post_search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}


{% block content %}

    <h1>Search</h1>

<h1> {{ time_now|date:'d F Y, H:i' }} UTC time</h1>

    <hr>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

    <hr>

{% if posts %}
<h3>
    {% if filterset.qs|length > 1 %}
      {{ filterset.qs|length }} posts found:
    {% elif filterset.qs|length == 1 %}
      Only 1 post found
    {% elif filterset.qs|length == 0 %}
      No posts found!
    {% endif %}
</h3>
<hr>

<table border="1" width="100%" cellpadding="5" rules="3">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Date</th>
            <th>Preview</th>
            <th>Category</th>
            <th>Rating</th>
        </tr>
{% for post in posts %}
        <tr>
                <td><a href="{% url 'news:author_name' post.author_id %}">{{ post.author }}</td>
                <td><a href="{% url 'news:post_detail' post.id %}"><class="post-title">{{ post.title|censor }}</td>
                <td>{{ post.time_pub|date:'d M Y H:i' }}</td>
                <td>{{ post.body|truncatechars:30|censor }}</td>
                <td>{% for cat in post.cats.all %}
                    <a href="{% url 'news:post_tag' cat.id %}">
                        {{ cat }}</a> :
                        <a></a>
                    {% endfor %}</td>
                <td>{{ post.rating }}</td>
        </tr>
{% endfor %}
</table>
{% else %}
    <h2>Nothing found!</h2>
{% endif %}
    <hr>


<nav aria-label="Page navigation">   <ul class="pagination">
{% if page_obj.has_previous %}
<li class="page-item">
  <a class="page-link" href="?{% url_replace page=1 %}" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
    <span class="sr-only">First</span>
  </a>
</li>   {% endif %}

{% for n in page_obj.paginator.page_range %}
  {% if page_obj.number == n %}
    <li class="page-item active">
      <span class="page-link">{{ n }}<span class="sr-only"> (this page)</span></span>
    </li>
  {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
    <li class="page-item"><a class="page-link" href="?{% url_replace page=n %}">{{ n }}</a></li>
  {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      <span class="sr-only">Last</span>
    </a>
  </li>
  {% endif %}   </ul> </nav>

{% endblock content %}

templates/posts.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

<!-- Название у нас будет Posts -->
{% block title %}
    <h1>Posts</h1>
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
<h1> {{ time_now|date:'d F Y, H:i' }} MSK</h1>

<h1>
    {% if qs_len > 1 %}
      There are {{ qs_len }} posts in the DB
    {% elif qs_len == 1 %}
      There is only 1 post in the DB
    {% elif qs_len == 0 %}
      There are no posts in the DB
    {% endif %}

</h1>

<!--   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}-->
<!--   <form action="" method="get">-->
<!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
<!--       {{ filterset.form.as_p }}-->
<!--       {# Добавим кнопку отправки данных формы #}-->
<!--       <input type="submit" value="Найти" />-->
<!--   </form>-->

<hr>
{% if posts %}
    <table border="1" width="100%" cellpadding="5">
      <thead>
        <tr>
            <th>Author</th>
            <th>Title</th>
            <th>Date</th>
            <th>Preview</th>
            <th>Category</th>
            <th>Rating</th>
            <th># of comments</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
            <tr>
                <td><a href="{% url 'news:author_name' post.author_id %}"> {{ post.author }}</td>
                <td><a href="{% url 'news:post_detail' post.id %}"> {{ post.title|censor }}</td>
                <td>{{ post.time_pub|date:'d M Y H:i' }}</td>
                <td>{{ post.body|truncatechars:30|censor }}</td>
                <td>{% for cat in post.cats.all %}
                    <a href="{% url 'news:post_tag' cat.id %}">
                        {{ cat }}</a> :
                        <a></a>
                    {% endfor %}</td>
                <td>{{ post.rating }}</td>
                <td>{{ post.comment_set.all|length }}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>

{% else %}
    <h2>There are no news!</h2>
{% endif %}


   {# Добавляем пагинацию на страницу #}

     <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="?{% url_replace page=1 %}" tabindex="-1">FIRST</a>
            </li>
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?{% url_replace page=page_obj.previous_page_number %}{% endif %} " tabindex="-1">Previous</a>
            </li>

            {% if page_obj.number|add:'-4' > 1 %}
                <li class="page-item disabled"><a class="page-link" href="?{% url_replace page=page_obj.number|add:'-5' %}">&hellip;</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item disabled"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
                {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                    <li class="page-item"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                <li class="page-item disabled"><a class="page-link" href="?{% url_replace page=page_obj.number|add:'5' %}">&hellip;</a></li>
            {% endif %}

            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} ?{% url_replace page=page_obj.next_page_number %} {% endif %}">Next</a>
            </li>
            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} ?{% url_replace page=page_obj.paginator.num_pages %}  {% endif %}">LAST</a>
            </li>
        </ul>
    </nav>

<!--ОЧЕНЬ КРАСИВЫЙ РАБОЧИЙ ВАРИАНТ-->

<!--<nav aria-label="Page navigation">   <ul class="pagination">-->
<!--{% if page_obj.has_previous %}-->
<!--<li class="page-item">-->
<!--  <a class="page-link" href="?page=1" aria-label="Previous">-->
<!--    <span aria-hidden="true">&laquo;</span>-->
<!--    <span class="sr-only">begin</span>-->
<!--  </a>-->
<!--</li>   {% endif %}-->

<!--{% for n in page_obj.paginator.page_range %}-->
<!--  {% if page_obj.number == n %}-->
<!--    <li class="page-item active">-->
<!--      <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>-->
<!--    </li>-->
<!--  {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}-->
<!--    <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>-->
<!--  {% endif %}-->
<!--{% endfor %}-->

<!--{% if page_obj.has_next %}-->
<!--  <li class="page-item">-->
<!--    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">-->
<!--      <span aria-hidden="true">&raquo;</span>-->
<!--      <span class="sr-only">end</span>-->
<!--    </a>-->
<!--  </li>-->
<!--  {% endif %}   </ul> </nav>-->


<!--КАК ДАНО В МОДУЛЕ-->

<!--{% if is_paginated %}-->
<!--   {# Информация о предыдущих страницах #}-->
<!--   {% if page_obj.has_previous %}-->
<!--       <a href="?{% url_replace page=1 %}">1</a>-->
<!--       {% if page_obj.previous_page_number != 1 %}-->
<!--           ...-->
<!--           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>-->
<!--       {% endif %}-->
<!--   {% endif %}-->

<!--   {# Информация о текущей странице #}-->
<!--   {{ page_obj.number }}-->

<!--   {# Информация о следующих страницах #}-->
<!--   {% if page_obj.has_next %}-->
<!--       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>-->
<!--       {% if paginator.num_pages != page_obj.next_page_number %}-->
<!--           ...-->
<!--           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>-->
<!--       {% endif %}-->
<!--   {% endif %}-->
<!--{% endif %}-->

{% endblock content %}

templates/weekly_digest.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Digest</title>
</head>

<body>
  <h1>News Portal weekly digest</h1>
  {% for category in category_object %}
      <p>There are new posts</p>
      <p>in category: <strong>"{{ category }}"</strong></p>
      {% for post in post_object %}
          {% for cat in post.cats.all %}
              {% if cat == category %}
                  <a href="https://newsportal.com{% url 'news:post_detail' post.id %}">
                    <h2>{{ post.title }}</h2>
                  </a>
                  <p>by {{ post.author }}</p>
                  <p>{{ post.email_preview }}</p>
              {% endif %}
          {% endfor %}
      {% endfor %}
  {% endfor %}
</body>

</html>